### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by mytestlabqa** [jamesjarvis/git-art#76]
Looks like fixed by GitHub.
All commits shown in history as todays.

**Comment by jamesjarvis** [comment]
Damn maybe they updated it to show when commits were pushed to github rather than an arbitrary commit time 😢

**Comment by jamesjarvis** [comment]
can confirm, still works: https://github.com/jamesjarvis/gitart2021
<img width="640" alt="image" src="https://user-images.githubusercontent.com/22618981/149848700-f1c2cfec-46d7-4930-937f-99c75712008a.png">
